name: Continious Deployment

on:
  push:
    branches:
      - master

jobs:
  if: false  # tmp on pause
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest
            docker stop ${{ secrets.DOCKER_IMAGE }} || true
            docker rm ${{ secrets.DOCKER_IMAGE }} || true
            docker run -d --name ${{ secrets.DOCKER_IMAGE }} \
                --network host --env-file ${{ secrets.SERVER_ENV_FILE_PATH }}\
                ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}:latest \
                uvicorn main:app --host 0.0.0.0 --port ${{ secrets.APP_PORT }} --workers ${{ secrets.WORKERS }}

